# Generated by Django 3.2.7 on 2024-05-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidpref', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
