# Generated by Django 3.2.7 on 2024-05-22 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidpref', '0004_auto_20240522_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_preference',
        ),
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
