# Generated by Django 3.2.7 on 2024-05-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidpref', '0006_rename_genre_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vidpref.user'),
            preserve_default=False,
        ),
    ]
