# Generated by Django 3.2.7 on 2024-05-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidpref', '0007_auto_20240522_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('News', 'News'), ('Comedy', 'Comedy'), ('Infotainment', 'Infotainment'), ('Entertainment', 'Entertainment'), ('Romance', 'Romance'), ('Tech', 'Tech'), ('SciFi', 'SciFi'), ('Movies', 'Movies'), ('Thriller', 'Thriller')], max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preference',
            field=models.CharField(choices=[('News', 'News'), ('Comedy', 'Comedy'), ('Infotainment', 'Infotainment'), ('Entertainment', 'Entertainment'), ('Romance', 'Romance'), ('Tech', 'Tech'), ('SciFi', 'SciFi'), ('Movies', 'Movies'), ('Thriller', 'Thriller')], max_length=20, unique=True),
        ),
    ]
