# Generated by Django 3.2.7 on 2024-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidpref', '0009_videostatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='preference',
            field=models.CharField(choices=[('News', 'News'), ('Comedy', 'Comedy'), ('Infotainment', 'Infotainment'), ('Entertainment', 'Entertainment'), ('Romance', 'Romance'), ('Tech', 'Tech'), ('SciFi', 'SciFi'), ('Movies', 'Movies'), ('Thriller', 'Thriller')], db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Comedy', 'Comedy'), ('Infotainment', 'Infotainment'), ('Entertainment', 'Entertainment'), ('Romance', 'Romance'), ('Tech', 'Tech'), ('SciFi', 'SciFi'), ('Movies', 'Movies'), ('Thriller', 'Thriller')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='videostatistics',
            name='interaction_type',
            field=models.CharField(choices=[('View', 'View'), ('Share', 'Share'), ('Download', 'Download')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='preferences',
            index=models.Index(fields=['user'], name='vidpref_pre_user_id_801d47_idx'),
        ),
        migrations.AddIndex(
            model_name='preferences',
            index=models.Index(fields=['preference'], name='vidpref_pre_prefere_14b3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='vidpref_use_usernam_28a2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='vidpref_use_email_41963e_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='vidpref_vid_categor_60d0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='videostatistics',
            index=models.Index(fields=['video'], name='vidpref_vid_video_i_9b05eb_idx'),
        ),
        migrations.AddIndex(
            model_name='videostatistics',
            index=models.Index(fields=['user'], name='vidpref_vid_user_id_3adad2_idx'),
        ),
        migrations.AddIndex(
            model_name='videostatistics',
            index=models.Index(fields=['interaction_type'], name='vidpref_vid_interac_1f7e40_idx'),
        ),
        migrations.AddIndex(
            model_name='videostatistics',
            index=models.Index(fields=['timestamp'], name='vidpref_vid_timesta_b1aab0_idx'),
        ),
    ]
